In [6]:
import pandas as pd

In [9]:
df=pd.read_csv('/content/Salary_Dataset_DataScienceLovers.csv')

In [11]:
df

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android
...,...,...,...,...,...,...,...,...
22765,4.7,Expert Solutions,Web Developer,200000,1,Bangalore,Full Time,Web
22766,4.0,Nextgen Innovation Labs,Web Developer,300000,1,Bangalore,Full Time,Web
22767,4.1,Fresher,Full Stack Web Developer,192000,13,Bangalore,Full Time,Web
22768,4.1,Accenture,Full Stack Web Developer,300000,7,Bangalore,Full Time,Web
22769,3.8,Thomson Reuters,Associate Web Developer,300000,7,Bangalore,Full Time,Web

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22770 entries, 0 to 22769
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rating             22770 non-null  float64
 1   Company Name       22769 non-null  object
 2   Job Title          22770 non-null  object
 3   Salary             22770 non-null  int64
 4   Salaries Reported  22770 non-null  int64
 5   Location           22770 non-null  object
 6   Employment Status  22770 non-null  object
 7   Job Roles          22770 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.4+ MB

In [15]:
df.isnull().sum()

Rating               0
Company Name         1
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64

In [16]:
company_name_mode = df['Company Name'].mode()[0]
df['Company Name'].fillna(company_name_mode, inplace=True)

/tmp/ipykernel_478/4168743280.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Company Name'].fillna(company_name_mode, inplace=True)

In [17]:
df.isnull().sum()

Rating               0
Company Name         0
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64

In [18]:
df.drop_duplicates()

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android
...,...,...,...,...,...,...,...,...
22765,4.7,Expert Solutions,Web Developer,200000,1,Bangalore,Full Time,Web
22766,4.0,Nextgen Innovation Labs,Web Developer,300000,1,Bangalore,Full Time,Web
22767,4.1,Fresher,Full Stack Web Developer,192000,13,Bangalore,Full Time,Web
22768,4.1,Accenture,Full Stack Web Developer,300000,7,Bangalore,Full Time,Web
22769,3.8,Thomson Reuters,Associate Web Developer,300000,7,Bangalore,Full Time,Web

In [48]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']

# Instantiate a new LabelEncoder for each column to ensure proper transformation
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
print('Categorical columns in df have been label encoded.')

Categorical columns in df have been label encoded.

In [19]:
print('DataFrame after Label Encoding:')
display(df.head())
print('\nUpdated DataFrame Info:')
df.info()

DataFrame after Label Encoding:

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android

Updated DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22770 entries, 0 to 22769
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rating             22770 non-null  float64
 1   Company Name       22770 non-null  object
 2   Job Title          22770 non-null  object
 3   Salary             22770 non-null  int64
 4   Salaries Reported  22770 non-null  int64
 5   Location           22770 non-null  object
 6   Employment Status  22770 non-null  object
 7   Job Roles          22770 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.4+ MB

In [21]:
X = df.drop('Salary', axis=1)
y = df['Salary']

In [22]:
X = df.drop('Salary', axis=1)
y = df['Salary']
print('Input variables (X):')
display(X.head())
print('\nOutput variable (y):')
display(y.head())

Input variables (X):

,Rating,Company Name,Job Title,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,3,Bangalore,Full Time,Android

Output variable (y):

0     400000
1     400000
2    1000000
3     300000
4     600000
Name: Salary, dtype: int64

In [55]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
print('Linear Regression model trained successfully.')

ValueError: could not convert string to float: 'Xome'

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

Shape of X_train: (18216, 7)
Shape of X_test: (4554, 7)
Shape of y_train: (18216,)
Shape of y_test: (4554,)

In [64]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)
print('Decision Tree Regressor model trained successfully.')

Decision Tree Regressor model trained successfully.

In [65]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)
print('Random Forest Regressor model trained successfully.')

Random Forest Regressor model trained successfully.

In [66]:
from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)
print('K-Nearest Neighbors Regressor model trained successfully.')

K-Nearest Neighbors Regressor model trained successfully.

In [67]:
from sklearn.svm import SVR

svm_model = SVR()
svm_model.fit(X_train, y_train)
print('Support Vector Machine Regressor model trained successfully.')

Support Vector Machine Regressor model trained successfully.

In [68]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pandas as pd

# Initialize lists to store metrics
model_names = []
r2_scores = []
maes = []
mses = []

# Evaluate Linear Regression model
if 'linear_model' in locals():
    y_pred_lr = linear_model.predict(X_test)
    model_names.append('Linear Regression')
    r2_scores.append(r2_score(y_test, y_pred_lr))
    maes.append(mean_absolute_error(y_test, y_pred_lr))
    mses.append(mean_squared_error(y_test, y_pred_lr))

# Evaluate Decision Tree Regressor model
if 'dt_model' in locals():
    y_pred_dt = dt_model.predict(X_test)
    model_names.append('Decision Tree Regressor')
    r2_scores.append(r2_score(y_test, y_pred_dt))
    maes.append(mean_absolute_error(y_test, y_pred_dt))
    mses.append(mean_squared_error(y_test, y_pred_dt))

# Evaluate Random Forest Regressor model
if 'rf_model' in locals():
    y_pred_rf = rf_model.predict(X_test)
    model_names.append('Random Forest Regressor')
    r2_scores.append(r2_score(y_test, y_pred_rf))
    maes.append(mean_absolute_error(y_test, y_pred_rf))
    mses.append(mean_squared_error(y_test, y_pred_rf))

# Evaluate K-Nearest Neighbors Regressor model
if 'knn_model' in locals():
    y_pred_knn = knn_model.predict(X_test)
    model_names.append('K-Nearest Neighbors Regressor')
    r2_scores.append(r2_score(y_test, y_pred_knn))
    maes.append(mean_absolute_error(y_test, y_pred_knn))
    mses.append(mean_squared_error(y_test, y_pred_knn))

# Evaluate Support Vector Machine Regressor model
if 'svm_model' in locals():
    y_pred_svm = svm_model.predict(X_test)
    model_names.append('Support Vector Machine Regressor')
    r2_scores.append(r2_score(y_test, y_pred_svm))
    maes.append(mean_absolute_error(y_test, y_pred_svm))
    mses.append(mean_squared_error(y_test, y_pred_svm))

# Create a DataFrame to display the results
metrics_df = pd.DataFrame({
    'Model': model_names,
    'R2 Score': r2_scores,
    'MAE': maes,
    'MSE': mses
})

display(metrics_df.sort_values(by='R2 Score', ascending=False))

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [70]:
import pickle
import pandas as pd

# Re-train Linear Regression model to ensure it's available for evaluation
# (This assumes X_train, y_train are available from previous steps)
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
print('Linear Regression model re-trained successfully.')

# Re-evaluate all models to get an up-to-date metrics_df
# (This code block is adapted from cell 36f83f8c)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

model_names = []
r2_scores = []
maes = []
mses = []

# Evaluate Linear Regression model
y_pred_lr = linear_model.predict(X_test)
model_names.append('Linear Regression')
r2_scores.append(r2_score(y_test, y_pred_lr))
maes.append(mean_absolute_error(y_test, y_pred_lr))
mses.append(mean_squared_error(y_test, y_pred_lr))

# Evaluate Decision Tree Regressor model
if 'dt_model' in locals(): # Ensure dt_model exists from previous training
    y_pred_dt = dt_model.predict(X_test)
    model_names.append('Decision Tree Regressor')
    r2_scores.append(r2_score(y_test, y_pred_dt))
    maes.append(mean_absolute_error(y_test, y_pred_dt))
    mses.append(mean_squared_error(y_test, y_pred_dt))

# Evaluate Random Forest Regressor model
if 'rf_model' in locals(): # Ensure rf_model exists from previous training
    y_pred_rf = rf_model.predict(X_test)
    model_names.append('Random Forest Regressor')
    r2_scores.append(r2_score(y_test, y_pred_rf))
    maes.append(mean_absolute_error(y_test, y_pred_rf))
    mses.append(mean_squared_error(y_test, y_pred_rf))

# Evaluate K-Nearest Neighbors Regressor model
if 'knn_model' in locals(): # Ensure knn_model exists from previous training
    y_pred_knn = knn_model.predict(X_test)
    model_names.append('K-Nearest Neighbors Regressor')
    r2_scores.append(r2_score(y_test, y_pred_knn))
    maes.append(mean_absolute_error(y_test, y_pred_knn))
mses.append(mean_squared_error(y_test, y_pred_knn))

# Evaluate Support Vector Machine Regressor model
if 'svm_model' in locals(): # Ensure svm_model exists from previous training
    y_pred_svm = svm_model.predict(X_test)
    model_names.append('Support Vector Machine Regressor')
    r2_scores.append(r2_score(y_test, y_pred_svm))
    maes.append(mean_absolute_error(y_test, y_pred_svm))
    mses.append(mean_squared_error(y_test, y_pred_svm))

metrics_df = pd.DataFrame({
    'Model': model_names,
    'R2 Score': r2_scores,
    'MAE': maes,
    'MSE': mses
})

display(metrics_df.sort_values(by='R2 Score', ascending=False))

# Identify the best model based on R2 Score
best_model_row = metrics_df.loc[metrics_df['R2 Score'].idxmax()]
best_model_name = best_model_row['Model']

# Get the actual best model object
best_model = None
if best_model_name == 'Linear Regression':
    best_model = linear_model
elif best_model_name == 'Decision Tree Regressor':
    best_model = dt_model
elif best_model_name == 'Random Forest Regressor':
    best_model = rf_model
elif best_model_name == 'K-Nearest Neighbors Regressor':
    best_model = knn_model
elif best_model_name == 'Support Vector Machine Regressor':
    best_model = svm_model

if best_model is not None:
    # Save the best model to a .pkl file
    filename = f'{best_model_name.replace(" ", "_").lower()}_model.pkl'
    with open(filename, 'wb') as file:
        pickle.dump(best_model, file)
    print(f'Best model ({best_model_name}) saved successfully to {filename}')
else:
    print('Could not identify or save the best model.')

Linear Regression model re-trained successfully.

                              Model  R2 Score            MAE           MSE
0                 Linear Regression  0.046720  414592.233988  3.865459e+11
4  Support Vector Machine Regressor -0.087549  399705.666771  4.409907e+11
3     K-Nearest Neighbors Regressor -0.530455  435852.998858  6.205848e+11
2           Random Forest Regressor -0.538862  399743.102890  6.239938e+11
1           Decision Tree Regressor -5.126940  526871.455424  2.484415e+12

Best model (Linear Regression) saved successfully to linear_regression_model.pkl

In [61]:
print('Re-executing data preparation cells to ensure correct encoding and split:')
# Re-apply Label Encoding to ensure df is fully numerical before splitting
# This code was already in ec54bd36, executing it here explicitly
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
print('Categorical columns in df have been label encoded again.')

# Now split into X and y from the fully encoded df
X = df.drop('Salary', axis=1)
y = df['Salary']

print('\nDataFrame dtypes after encoding and before X, y split:')
display(df.dtypes)
print('\nInput variables (X) dtypes:')
display(X.dtypes)
print('\nOutput variable (y) head:')
display(y.head())

Re-executing data preparation cells to ensure correct encoding and split:
Categorical columns in df have been label encoded again.

DataFrame dtypes after encoding and before X, y split:

Rating               float64
Company Name           int64
Job Title              int64
Salary                 int64
Salaries Reported      int64
Location               int64
Employment Status      int64
Job Roles              int64
dtype: object

Input variables (X) dtypes:

Rating               float64
Company Name           int64
Job Title              int64
Salaries Reported      int64
Location               int64
Employment Status      int64
Job Roles              int64
dtype: object

Output variable (y) head:

0     400000
1     400000
2    1000000
3     300000
4     600000
Name: Salary, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('Train-test split performed successfully.')

Train-test split performed successfully.

In [63]:
print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

print('\nNow you can try running the model training cell `79458dda` again.')

Shape of X_train: (18216, 7)
Shape of X_test: (4554, 7)
Shape of y_train: (18216,)
Shape of y_test: (4554,)

Now you can try running the model training cell `79458dda` again.